# Generated by Django 5.0.3 on 2024-04-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
