# Generated by Django 5.0.3 on 2024-04-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheatsheet',
            options={'verbose_name': 'Загрузить файл', 'verbose_name_plural': 'Загрузить файлы'},
        ),
    ]
